Update deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -31,7 +31,7 @@ jobs:
       - name: Build userService
         run: mvn -e -B package --file userService/pom.xml  # Собрать проект Maven, указав путь к pom.xml
 
-      - name: List built files
+      - name: List built files for userService
         run: ls -la userService/target  # Показать список файлов в целевой папке после сборки
 
       - name: Deploy userService to Server
@@ -41,7 +41,7 @@ jobs:
           username: ${{ secrets.SERVER_USERNAME }}
           key: ${{ secrets.SSH_PRIVATE_KEY }}
           source: 'userService/target/userService-0.0.1-SNAPSHOT.jar'  # Указать путь к скомпилированному JAR файлу
-          target: '/home/xyl1gan4eg/myJavaProjects/weatherProject'  # Указать целевой путь на сервере
+          target: '/home/xyl1gan4eg/myJavaProjects/weatherProject/userService'  # Указать целевой путь на сервере
           port: 22
           timeout: 30s
           command_timeout: 10m
@@ -56,7 +56,6 @@ jobs:
           proxy_timeout: 30s
           proxy_use_insecure_cipher: false  # Настройки для scp-action, чтобы копировать файл на удаленный сервер
 
-
       - name: SSH into server and restart userService
         uses: appleboy/ssh-action@master
         with:
@@ -65,19 +64,65 @@ jobs:
           key: ${{ secrets.SSH_PRIVATE_KEY }}
           script: |
             echo "Checking for JAR file..."
-            if [ -f /home/xyl1gan4eg/myJavaProjects/weatherProject/userService/target/userService-0.0.1-SNAPSHOT.jar ]; then
+            if [ -f /home/xyl1gan4eg/myJavaProjects/weatherProject/userService/userService-0.0.1-SNAPSHOT.jar ]; then
               echo "JAR file found. Proceeding with service restart."
               if sudo systemctl is-active --quiet user-service; then
                 sudo systemctl stop user-service
               fi
-              sudo cp /home/xyl1gan4eg/myJavaProjects/weatherProject/userService/targer/userService-0.0.1-SNAPSHOT.jar /opt/userService/
+              sudo cp /home/xyl1gan4eg/myJavaProjects/weatherProject/userService/userService-0.0.1-SNAPSHOT.jar /opt/userService/
               sudo systemctl start user-service
             else
               echo "JAR file not found!"
               exit 1
             fi
 
+      - name: Build weatherApiService
+        run: mvn -e -B package --file weatherApiService/pom.xml  # Собрать проект Maven, указав путь к pom.xml
 
+      - name: List built files for weatherApiService
+        run: ls -la weatherApiService/target  # Показать список файлов в целевой папке после сборки
+
+      - name: Deploy weatherApiService to Server
+        uses: appleboy/scp-action@master
+        with:
+          host: ${{ secrets.SERVER_HOST }}
+          username: ${{ secrets.SERVER_USERNAME }}
+          key: ${{ secrets.SSH_PRIVATE_KEY }}
+          source: 'weatherApiService/target/weatherApiService-0.0.1-SNAPSHOT.jar'  # Указать путь к скомпилированному JAR файлу
+          target: '/home/xyl1gan4eg/myJavaProjects/weatherProject/weatherApiService'  # Указать целевой путь на сервере
+          port: 22
+          timeout: 30s
+          command_timeout: 10m
+          use_insecure_cipher: false
+          rm: false
+          debug: false
+          strip_components: 0
+          overwrite: true
+          tar_dereference: false
+          tar_exec: tar
+          proxy_port: 22
+          proxy_timeout: 30s
+          proxy_use_insecure_cipher: false  # Настройки для scp-action, чтобы копировать файл на удаленный сервер
+
+      - name: SSH into server and restart weatherApiService
+        uses: appleboy/ssh-action@master
+        with:
+          host: ${{ secrets.SERVER_HOST }}
+          username: ${{ secrets.SERVER_USERNAME }}
+          key: ${{ secrets.SSH_PRIVATE_KEY }}
+          script: |
+            echo "Checking for JAR file..."
+            if [ -f /home/xyl1gan4eg/myJavaProjects/weatherProject/weatherApiService/weatherApiService-0.0.1-SNAPSHOT.jar ]; then
+              echo "JAR file found. Proceeding with service restart."
+              if sudo systemctl is-active --quiet weather-api-service; then
+                sudo systemctl stop weather-api-service
+              fi
+              sudo cp /home/xyl1gan4eg/myJavaProjects/weatherProject/weatherApiService/weatherApiService-0.0.1-SNAPSHOT.jar /opt/weatherApiService/
+              sudo systemctl start weather-api-service
+            else
+              echo "JAR file not found!"
+              exit 1
+            fi
 
       - name: List files on server for debug
         uses: appleboy/ssh-action@master
@@ -88,3 +133,5 @@ jobs:
           script: |
             echo "Listing files in /home/xyl1gan4eg/myJavaProjects/weatherProject/userService/"
             ls -la /home/xyl1gan4eg/myJavaProjects/weatherProject/userService/  # Показать список файлов в целевой папке для отладки
+            echo "Listing files in /home/xyl1gan4eg/myJavaProjects/weatherProject/weatherApiService/"
+            ls -la /home/xyl1gan4eg/myJavaProjects/weatherProject/weatherApiService/  # Показать список файлов в целевой папке для отладки
