Update deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -28,14 +28,20 @@ jobs:
       - name: Debug environment variables
         run: printenv
 
-      - name: Deploy project files to server
+      - name: Build userService
+        run: mvn -e -X -B package --file userService/pom.xml
+
+      - name: List built files
+        run: ls -la userService/target
+
+      - name: Deploy userService to Server
         uses: appleboy/scp-action@master
         with:
           host: ${{ secrets.SERVER_HOST }}
           username: ${{ secrets.SERVER_USERNAME }}
           key: ${{ secrets.SSH_PRIVATE_KEY }}
-          source: '.'
-          target: '/home/xyl1gan4eg/myJavaProjects/weatherProject'
+          source: 'userService/target/*.jar'
+          target: '/home/xyl1gan4eg/myJavaProjects/weatherProject/userService/userService.jar'
           port: 22
           timeout: 30s
           command_timeout: 10m
@@ -50,17 +56,22 @@ jobs:
           proxy_timeout: 30s
           proxy_use_insecure_cipher: false
 
-      - name: SSH into server, build and restart userService
+      - name: SSH into server and restart userService
         uses: appleboy/ssh-action@master
         with:
           host: ${{ secrets.SERVER_HOST }}
           username: ${{ secrets.SERVER_USERNAME }}
           key: ${{ secrets.SSH_PRIVATE_KEY }}
           script: |
-            cd /home/xyl1gan4eg/myJavaProjects/weatherProject
-            mvn clean package --file userService/pom.xml
-            if sudo systemctl is-active --quiet user-service; then
-              sudo systemctl stop user-service
+            echo "Checking for JAR file..."
+            if [ -f /home/xyl1gan4eg/myJavaProjects/weatherProject/userService/userService.jar ]; then
+              echo "JAR file found. Proceeding with service restart."
+              if sudo systemctl is-active --quiet user-service; then
+                sudo systemctl stop user-service
+              fi
+              sudo cp /home/xyl1gan4eg/myJavaProjects/weatherProject/userService/userService.jar /opt/userService/
+              sudo systemctl start user-service
+            else
+              echo "JAR file not found!"
+              exit 1
             fi
-            sudo cp /home/xyl1gan4eg/myJavaProjects/weatherProject/userService/target/userService.jar /opt/userService/
-            sudo systemctl start user-service
